version: '2'

services:
  business_microservice:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  cpu_microservice:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  memory_microservice:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  io_microservice:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
